server:
  port: 8761
spring:
  application:
    name: miracle-registry
  security:
    user:
      name: miracle
      password: 123456
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    renewal-percent-threshold: 0.65
    renewal-threshold-update-interval-ms: 3000
  instance:
    prefer-ip-address: true
